---
output:
  pdf_document: default
  html_document: default
---
# Preface

## What is this?

This is the textbook for Prof. Westberg's *Introduction to Macroeconomics* course. It is a book for college students, not for college profs. This book will be published as an open-source text when it is complete. It is ultimately intended to help my students learn how the economy works, how that affects their lives, and what they can do about it. 

I'll cut to the quick: the Economy does what it is designed to do. Many of my economic colleagues would disagree with that statement, but look at the structure of unemployment by race, age, gender, and class over the past 18 years of your lives and ask a simple question: Why doesn't this ever change? 

It isn't because there is something inherently different in the productivity of these groups. Rather, it's grounded in the different ways that these groups are perceived in economic (and social-political) situations. In other words, these groups are treated differently by the economy because the people who ultimately wrote and are rewriting the economic rules see those groups differently. Whether they realize it or not, the rule writers almost always write rules to benefit their own groups.^[For readers who really want to dive into this right away, I urge you to download Chelwa, Hamilton, and Stewarts latest work on [**Stratification Economics**](https://www.aeaweb.org/articles?id=10.1257/jel.20211687).] 

We live in highly politicized times. I have no doubt that many of you reading this have already formed some idea of what is in this book, and this class, from the preceding paragraph. Let me, perhaps, surprise you: whether you think this book will fit into some lefty-liberal agenda or some right-wing populist revolt, you'd be right. This book is political. All books are. But, the approach I will teach you forces all of us to engage our core beliefs, to interrogate them, and to be willing to find them lacking. What if your most cherished political belief turns out to be useless at best (i.e. "free markets") or just flat out wrong at worst (i.e. "banks lend out of deposits")? Well, in this class, you'll learn to accept it and move on. My only ask of you this: recognize you come to this class with your own ideology, beliefs, and expectations - we all do, including me! - but be willing to take these on. Be skeptical but learn to be logical.

This book is intended to give you to the tools to understand how the economy is designed to work, what drives it, and how that shapes the world we live in. My sincere hope is that you are one day able to use it to reshape the economy to produce the kind of outcomes that you want to see in the world your generation constructs. I believe it is possible; I hope you do to.  

## Who am I?

I have been teaching *Principles of Macroeconomics* for nearly a decade now. I've taught the course over 30 times to nearly 1,000 students. In that time, I have moved farther and farther away from standard Macroeconomics textbooks, pushing my course content to more aptly reflect the pressing questions of today's students: climate change, income inequality, racial justice, power, and money (interest in that one never seems to go away :) ). That move has been a success both in terms of student achievement and student satisfaction. In fact, in 2021 I was honored to receive the Charles J. Lynch Outstanding Teacher Award at Coe College. I say this to give you confidence in what I am teaching you. Whether you're a Democrat, a Republican, or something else entirely, the economy still shapes your life and I'm here to show you how that happens.

This book is about teaching and learning. It is meant to be accessible, not another barrier to learning challenging content. I will supplement it with recorded lectures, PowerPoint slides, and in-class discussions. But, the essentials of the content will be here. If you love math, there are chapters for you here. If you hate math but love story, there are chapters here for you too. And I promise to do my best to help both camps get through their respective fears.

I am also a father of two young, amazing humans: June and Michael. This book is as much for them as it is for you. I want them to live in a better world, a more just world, a sustainable world, and a world grounded in Democracy and equality of opportunity. They will live in the world you and I create...so the pressure, so to speak, is on. 

## Why this book?

There are two reasons for this book. First and foremost, it is for you. Part of my movement away from textbooks was the cost to students. It was pretty wild to ask students to pay hundreds for a textbook that didn't speak to them. It was a little better to just use old versions of those books to save money. But, those books have grown increasingly out of date and out of touch too. As I have continued to move away from textbooks in my class, it has made it more challenging for some students to stay connected to the material. Though PowerPoints can help, students need more and varied points of connection to both learn concepts and put them into practice. To that end, I have written this book for you (and it's free!).  Second, the standard macroeconomics textbook has grown increasingly vapid over time. College students today face a world of myriad crises: inequality, debt, guns, pandemics, declining psychological health, growing social dysfunction, and oh yeah, [the planet is on @#*%&@# fire (FYI the following link does contain explicit language from Bill Nye the Science Guy)](https://www.youtube.com/watch?v=IFgBFYkBZ6E). Yet, the current stock of macroeconomics textbooks won't teach you how to incorporate income distribution into the foundation of your analysis; they won't show you how the economy interacts with the environment; and they certainly won't help you understand the political economy of power. And so, my second purpose for this book is write a book that actually addresses some of the very real and daunting challenges that lie ahead for us: you, me, my children, and yours. This is a book about The Economy \& Us.

## My Approach

My approach to the economy and to teaching has been shaped by many economists across a wide range of so-called *schools of thought*. As a theorist though, I find myself coming back to the work of Elinor ("Lin") Ostrom, the first woman to win the coveted Nobel Prize in Economics.^[I encourage you to listen to her 2009 speech [here](https://www.nobelprize.org/prizes/economic-sciences/2009/ostrom/lecture/).] Though her award focused on her main academic conclusion - "complexity is not the same as chaos" - it is her approach to theory construction that has always stood out to me. Specifically, Prof. Ostrom argues that theory construction should rest on a specific architecture: a framework, a set of theories, and models that illustrate those theoretical connections. As noted by one of Ostrom's former colleagues, [Michael McGinnis (2011)](https://onlinelibrary.wiley.com/doi/abs/10.1111/j.1541-0072.2010.00401.x) a,  

  *   **Framework** identifies, categorizes, and organizes those factors deemed most relevant to understanding some phenomenon.
  *   **Theory** posits general causal relationships among some subsets of these variables or categories of factors, designating some types of factors as especially important and others as less critical for explanatory purposes.
  *   **Model** specifies the specific functional relationships among particular variables or indicators that are hypothesized to operate in some well-defined set of conditions.

We will rely on this architecture to structure the book and our examination of the various theoretical perspectives on "the economy". In doing so, my hope is that you will be better able to think critically about the economic answers that dominate our personal media environments. 

## Structure of the Book

The book will adhere to Ostrom's architecture. First, we will lay out the framework and attempt to fully understand its varied components, its data, and its definitions. Then we will move into the theory and modelling stages. In  Part I, we will spend some time learning to talk about what the economy is and what it does. Then, we will move to construct a framework of the economy. Initially, this framework will be quite incomplete. However, we will add to it as we move through the material, learning along the way just how important a framework is to problem solving and thinking through complexity.^[For those of you with little patience, the key takeaway is that our frameworks define what questions can be asked. For example, if the environment does not exist in your framework, then how important are you likely to think it is in effecting your problem of concern? Simply put, you would never even think to ask!]

With a framework of the macroeconomy in place, Part II of the book will move us into  **Classical Economic Theory**, i.e. the set of causal relationships between the variables in our framework that were adhered to (believed in?) by so-called "Classical Economists". This theoretical approach dominated economic theorizing for much of the 19^th^ and 20^th^ centuries. Once we understand the core Classical Theoretical beliefs, we will move to construct the **Classical Model**, which is an analytical tool that illustrates the Classical Theory in action. We will use this model to illustrate how economists think. We will explain the past, examine the present, and predict the future. 

The Classical Theory was a useful explanation of the economy for its time. But, as is typical in human history, this view of the world eventually stopped being able to explain it effectively. The Great Depression presented something that did not exist within Classical Theory - prolonged involuntary unemployment. Thankfully, a small cohort of economists in Britain had been slowly tearing themselves apart from this outdated view in the late 1920s and early 1930s. Three names in particular are worth mentioning here: Keynes, Kalecki, and Robinson. These economists helped shape and ultimately export what came to be known as "Keynesian Economics", the subject of Part III of the course, to the rest of the world.  Here, we will explore the emergence of a new set of theoretical propositions that came to be known as **Keynesian Theory**. This approach to the economy was quite different from Classical Theory. In almost every way, the Keynesian approach turned the Classical Theory upside down (or perhaps better described as "right-side up"). This new theory became dominant in most economic circles from the late 1930s into the late 1960s. From there, the theoretical paths diverged rather dramatically. 

Most economics textbooks take students down a path that frankly doesn't yield much fruit - and that's putting it rather kindly. Instead, this book will diverge at that point and move students' thinking toward more relevant questions of this age, using more comprehensive tools and more empirically validated theories. With these tools in place, we will explore big questions: What is the impact of income inequality on the economy? How can the economy and the environment be connected? Is there a connection between inequality writ large and the environmental catastrophe we are all living in the midst of already?

My hope is that you, the student, will find this material engaging, accessible, but most importantly, relevant. It will not be an easy journey, but deep learning never is. 

## The Importance of Goals

At this point, I'm going to ask you to read the *Introduction* and *Ch. 1 The Gross Domestic Product* out of an incredibly important book, [*What's the Economy For Anyway?*](https://www.amazon.com/Whats-Economy-Anyway-Pursuing-Happiness/dp/1608195155). The book asks a central question. The answer is for all of us to determine together and that is the power behind simply asking the question. It presumes that there can be an actual answer. The economy therefore is something we can shape, alter, re-orient. For most students and most adults quite frankly, this revelation is hard to fathom. In my experience, most students sense the economy as something like gravity, an external force that is shaping their lives but something far beyond their ability to influence. They just hope to hitch a good ride. The first chapter in that book shows you just how wrong that assumption is; it also helps you start to see how much it benefits political and economic elites when we succumb to this common belief. Once you see that in fact we can make substantive changes, my hope is that you will never "unsee it" again.

Let's look at some outcomes, economic outcomes. I want you to take a few minutes and go to the St. Louis Federal Reserve Bank's aptly named data center, [FRED](https://fred.stlouisfed.org/) and attempt to plot the following data series:

  *   Gross Domestic Output
  *   Unemployment Rate
  
We will dive into these measures in more detail in the next chapter. For now, I want you to look carefully at these two major measures that we use to manage the economy. Gross Domestic Product (GDP) measures the overall size of the economy. The Unemployment Rate tells you the percent (%) of all job seekers that aren't able to find work. These measures, coupled with inflation (again we will dive into that one shortly), give us the big three measures that Macroeconomists use to assess the overall health of the economy. If GDP is bigger than last month/quarter/year, if inflation is right around 2\%, and if the Unemployment Rate is around 5\%, most Macroeconomists would tell the economy is at *Full Employment*. Technically, they would tell you that the economy has reached its "Non-accelerating Inflation Rate of Unemployment", or put simply, there are enough unemployed people to keep prices from rising too fast. But, let me ask you a question: What is it that we are trying to achieve with an economic system managed around the idea of raising GDP and keeping prices low through a buffer of unemployed people? That's the big question: what is the goal? 

These measures of the economy are just measures. They are just indicators that the economy is doing what we have designed it to do. They are a means to some end. But what are the ends of the economy? What do we want it to do?

At this point, I've already put you in a mental box. Let me show you how. Quickly now, I want you to make a list of the five things you want the economy to do. Do it. Go fast. Now:

  1.
  2.
  3.
  4.
  5.
  
I'll bet that most, if not all of you put something about growth, unemployment, and inflation on your lists. You've confused economic measures with economic goals. It's okay. You've been trained to do that. Now, let's undue some of that training.

Step outside of the economy for a moment and do a different thought exercise with me. I want you to establish five goals for your life by answering this question: What are the five most important things you need to live a happy, healthy, and flourishing human life? Take your time this time. Think it through, carefully (I'll share my five things with you in class).

  1.
  2.
  3.
  4.
  5.
  
Now, how many of you wrote something like "Make the economy bigger"? I doubt any of you did and that's the point. The things that matter to you as human beings are much deaper things. Things that revolve around community connection, doing meaningful work, meeting new people and experiencing new places, etc. There is so much that goes into a flourishing human life, and frankly, not nearly enough of those things show up in our measures of the economy. GDP, unemployment, inflation, these are just measures, sign-posts that help us know if we are heading toward our goal(s) or if we are off track. Which brings us to the question of the day: based on the big three measures of the economy, can you tell me what the economic goal(s) is(are)? And, just who's goals are they?







  












